version: '2'

services:
    mongodb:
        image: mongo
        volumes: 
            - ./db:/data/db
        ports:
            - 27017:27017          

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        links:
            - mongodb:mongo

    lightmessageservice:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        links:
            - mongodb
        environment: 
            - PORT=3000
            - MONGODB_CONNECT=mongodb://mongodb:27017
            - MONGODB_DATABASE=lightmessage


